package:
  name: "climateserv"
  version: "1.0.5"

source:
  git_rev: v1.0.5
  git_url: https://github.com/SERVIR/ClimateSERVpy

build:
  number: 1
  noarch: python

requirements:
  build:
    - setuptools
  run:
    - python
    - requests

python:
  - 3.8

about:
  home: https://github.com/SERVIR/ClimateSERVpy
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "This is a package to access the ClimateSERV API](https://climateserv.servirglobal.net/)"

extra:
  recipe-maintainers:
    - SERVIR

test:
  commands:
    - python -m pip install .
    - pytest