package:
  name: "climateserv"
  version: "1.0.6"

source:
  git_rev: v1.0.7
  git_url: https://github.com/SERVIR/ClimateSERVpy

build:
  noarch: python
  number: 0
  script: python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

about:
  home: https://github.com/SERVIR/ClimateSERVpy
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "This is a package to access the ClimateSERV API](https://climateserv.servirglobal.net/)"

extra:
  recipe-maintainers:
    - SERVIR